language: node_js
dist: trusty
node_js:
  - "8"
install:
  - cd _hexo
  - npm install
script:
  - \cp -f ../_patch/index.js node_modules/hexo-prism-plugin/src/index.js
  - chmod +x ../deploy.sh
  - npm run build
  - ../deploy.sh > /dev/null
branches:
  only:
    - raw
cache:
  directories:
    - _hexo/node_modules
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
