# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "https://s.nfz.yecdn.com/favicon.ico"
    high_res_favicon: "https://s.nfz.yecdn.com/favicon.png"
    apple_touch_icon: "https://s.nfz.yecdn.com/favicon.png"
    keywords: "neoFelhz, blog, hexo, Android, Web, neo, 博客"
    site_verification:
        google: "o1-IzSRJ5n6Bn_94myQyxyyETTy4HFuJePSeemMT0Tc"
        baidu:

    # Enable generate structured-data as JSON+LD for SEO or not.
    #        Set as 'false' if it cause some wrong when `hexo g`.
    structured_data: true

# Jump Links Settings
url:
    rss: "//blog.nfz.moe/atom.xml"
    daily_pic: ""
    logo: "//nfz.moe"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
scheme: Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "孤独之人 不应执着 为何仍追逐幻梦"
    theme_color: "#546E7A"
    theme_sub_color: "#424242"
    hyperlink_color: "#607D8B"
    button_color: "#546E7A"
    android_chrome_color: "#455A64"
    nprogress_color: "#212121"
    nprogress_buffer: "350"

# JS Effect Switches
js_effect:
    fade: false
    smoothscroll: false

# Reading experience
reading:
    entry_excerpt: 100

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#EEEEEE"
    #bgimg: "/img/bg.png"
    bing:
        enable: false
        parameter:

# Images Settings
img:
    logo: "https://s.nfz.yecdn.com/favicon.png"
    avatar: "https://s.nfz.yecdn.com/img/avatar-m.png!t"
    daily_pic: "https://s.nfz.yecdn.com/img/d.jpg!t"
    sidebar_header: "https://s.nfz.yecdn.com/img/u.png!t"
    footerico: "https://s.nfz.yecdn.com/img/footer/footer_ico-"
    random_thumbnail: "https://s.nfz.yecdn.com/img/random/material-"
    footer_image:
        upyun_logo:
            link: "https://www.upyun.com/"
            src: 'https://s.nfz.yecdn.com/img/upyun_logo.svg'

# Custom Fonts
#   family: the font-family which will be used in the theme
#   host: uri of fonts host.
#       Available value of "host": google | baomitu | ustc | custom | catnet
#       When you configured 'use' as 'custom', you should fill in the value of 'custom_font_host', which should be a mirror of google fonts.
#        If you have setup your custom font-family, don't forget to add style tag with @font-face or link.tag with font css to /source/data/head.yml as custom code, to load custom font files.
fonts:
    family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Helvetica, Arial, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", SimSun, sans-serif
    use: catnet
    custom_font_host:

# Card Elevation Level
card_elevation: 2

# Copyright
# Specify the date when the site was setup.
#   For example, if you set it as 2015, then footer will show '© 2015 - 2017'
copyright_since: 2016

# Footer Text
# You can specify the text you want to show in footer, HTML tag is supported.
#   For example, you can setup ICP license number as:
#       '<a href="http://www.miitbeian.gov.cn" rel="nofollow">某ICP备xxxxxxxx号-x</a>'
footer_text:

# Qrcode for redirect at other device
#   use: choose which method to generate the qrcode for each posts.
#       Available value of "use": plugin | online
#           - When use "plugin", you need to install the hexo-helper-qrcode.
#           - When use "online", the qrcode will be generated by 'pan.baidu.com' in China.
qrcode:
    enable: false
    use: plugin

# Code highlight
# Available value for `prettify` or `hanabi`: true | false
# You can only enable one of them to avoid issues. Also you need to check highlight option in _config.yml. Make sure that default hexo built in highlight plugin is disabled.
#        highlight:
#            enable: false
#
#     Prettify
#         theme value:
#         theme-name  # /vendors/prettify/themes/[theme-name].css
prettify:
    enable: false
    theme: "vibrant-ink" # default value: "vibrant-ink"   # theme-name without '.css'

#     Hanabi
#         hanabi © egoist, Released under the MIT License
#         https://github.com/egoist/hanabi
#
#     line_number: [true/false] # Show line number for code block
#     includeDefaultColors: [true/false] # Use default hanabi colors
#     customColors:     # This value accept a string or am array to setting for hanabi colors.
#                       # If `includeDefaultColors` is true, this will append colors to the color pool
#                       # If `includeDefaultColors` is false, this will instead default color pool
hanabi:
    enable: false
    line_number: true
    includeDefaultColors: true
    customColors:

# Post License
# You can specify the text you want to show in the end of your posts and pages, HTML tag is supported.
#   For example, you can setup a CC license as:
#       'This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'
# You can also use Front-Matter `license` to override this setting.
license: "本文采用 <a rel='nofollow noopener' href='https://creativecommons.org/licenses/by-nc-sa/3.0/deed.zh' target='_blank'>CC BY-NC-SA 3.0 Unported</a> 协议进行许可，阅读 <a href='/creativecommons.html' target='_blank'>相关说明</a>"

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# TOC Button

toc:
#   use: choose whether the line_number of toc will show or not.
#       Available value of "linenumber": true | false
    linenumber: true

# SNS Menu
sns:
    email: neofelhz@gmail.com
    facebook:
    twitter:
    googleplus:
    weibo:
    instagram:
    tumblr:
    github: https://github.com/neoFelhz
    linkedin:
    zhihu: https://www.zhihu.com/people/neoFelhz
    bilibili:
    telegram: https://t.me/neoFelhz
    v2ex: https://www.v2ex.com/member/neoFelhz

# SNS Share Switch
sns_share:
    twitter: true
    facebook: false
    googleplus: true
    weibo: true
    linkedin: false
    qq: true
    telegram: true

# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "mailto:neofelhz@gmail.com"
            icon: email
        nfz.moe:
            link: "https://nfz.moe"
            icon: explorer
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: false
        icon: inbox
        divider: false
    categories:
        use: true
        icon: apps
        divider: false
    pages:
        归档:
            link: "/timeline.html"
            icon: inbox
            divider: true
        关于:
            link: "/about.html"
            icon: person
            divider: false
        标签:
            link: "/tags.html"
            icon: bookmark
            divider: false
        映像:
            link: "/gallery.html"
            icon: photo
            divider: false
        友链:
            link: "/links.html"
            icon: people
            divider: true
    article_num:
        use: true
        divider: false
    footer:
        divider: false
        theme: false
        support: false
        feedback: false
        material: false


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# Comment Systems
# Available value of "use":
#     disqus | disqus_click | changyan | livere | gitment | valine
# If you want to use gitment,you should get the client_id and client_secret form https://github.com/settings/applications/new
# If you want to use valine,you should get the app_id and app_key form https://leancloud.cn ,more setting please see https://github.com/xCss/Valine
comment:
    use: disqus_click
    shortname: neofelhzblog # duoshuo or disqus shortname
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    livere_data_uid:
    gitment_repo:   # git repo of the hexo
    gitment_owner:  # git repo's owner
    gitment_client_id:  # github app client id
    gitment_client_secret :  # github app client secret
    valine_leancloud_appId: # leancloud application app id
    valine_leancloud_appKey: # leancloud application app key

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: local
    swiftype_key:

# Analytics Systems
# Available value:
#     baidu | google | cnzz
analytics:
    google_site_id:
    baidu_site_id:
    cnzz_site_id:

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

# Files Vendors
# Set a CDN for the files src you want to customize. The url should with protocol.
# Default(empty) will load the files from the origin server.
vendors:
# MaterialCDN
#   You can load theme unique files from your private cdn or oss.
#   The new src will have the base domain you configured below.
#   For example
#       materialcdn: https://cdn.jsdelivr.net/npm/hexo-material@1.4.0/source
    materialcdn: https://s.nfz.yecdn.com

# Third party library
#   You can load these files from public cdn.
#   For example
#       jquery: https://cdn.bootcss.com/jquery/2.2.1/jquery.js
    # jQuery 2.2.0
    jquery:
    # nprogress 0.2.0
    nprogress:
    # FontAwesome 4.5.0
    fontawesome:
    # MathJax 2.7.0-2.7.1
    mathjax:
    # Prettify r298 (only prettify.js)
    prettify:
    # Material Icons 3.0.1
    material_icons:
